### ISSUE TITLE
Mixins "Global module exports may only appear in module files." after updating to v6.0.3

### ISSUE THREAD

**Issue by WillPoulson** [pixijs/pixi.js#7483]
### Expected Behavior
After upgrading from v6.0.2 to v6.0.3 the project will compile successfully.

### Current Behavior
When trying to compile I'm encountering the following issues
```
Error: node_modules/@pixi/mixin-get-child-by-name/index.d.ts:4:1 - error TS1314: Global module exports may only appear in module files.
4 export as namespace PIXI;
  ~~~~~~~~~~~~~~~~~~~~~~~~~
Error: node_modules/@pixi/mixin-get-global-position/index.d.ts:4:1 - error TS1314: Global module exports may only appear in module files.
4 export as namespace PIXI;
  ~~~~~~~~~~~~~~~~~~~~~~~~~
  ```

### Possible Solution
I'm not sure here, other mixins like cache as bitmap are working okay.

### Steps to Reproduce
Create a new angular 11 project. Install Pixi v6.0.3 and import it somewhere (possibly use the getChildByName function?)
When trying to compile you'll get the above error.

### Environment

- **`pixi.js` version**: 6.0.3
- **Browser & Version**: Chrome
- **OS & Version**: MacOS Big Sur

Please note this is an Angular 11 project. The steps have been followed from the original Pixi v6 migration guide in tsconfig.
