### ISSUE TITLE
4.5.0 Uncaught TypeError: this.fn is not a function

### ISSUE THREAD

**Issue by dan335** [pixijs/pixi.js#3936]
After upgrading to 4.5.0 I get this error.  Did not get the error in 4.4.4.

    8f7496c….js?meteor_js_resource=true:28 Uncaught TypeError: this.fn is not a function
    at t.emit (8f7496c….js?meteor_js_resource=true:28)
    at t.update (8f7496c….js?meteor_js_resource=true:28)
    at _tick (8f7496c….js?meteor_js_resource=true:28)

**Comment by bigtimebuddy** [comment]
Any more info you could provide about this issue? Like, when does it occur or how to reproduce? Or even better: if you can reproduce the error in a jsfiddle that's incredibly useful. Thanks for reporting!

**Comment by dan335** [comment]
It happens at line 100 here

````
  TickerListener.prototype.emit = function emit(deltaTime) {     // 96
    if (this.context) {                                          // 97
      this.fn.call(this.context, deltaTime);                     // 98
    } else {                                                     // 99
      this.fn(deltaTime);                                        // 100
    }                                                            // 101
                                                                 // 102
    if (this.once) {                                             // 103
      this.destroy();                                            // 104
    }                                                            // 105
                                                                 // 106
    var redirect = this.next;                                    // 107
                                                                 // 108
    // Soft-destroying should remove                             // 109
    // the next reference                                        // 110
    if (this._destroyed) {                                       // 111
      this.next = null;                                          // 112
    }                                                            // 113
                                                                 // 114
    return redirect;                                             // 115
  };   
````
Seems to happen right after an object is destroyed.

**Comment by bigtimebuddy** [comment]
What object is being destroyed?

**Comment by RFitz** [comment]
I just ran into this issue as well. 
Here is an example: https://jsfiddle.net/oqw8119u/

Seems like the this.next is being destroyed in the this.destroy() before it gets assigned to redirect.

I think if you move line 107 before 103 it will fix it.

**Comment by bigtimebuddy** [comment]
Confirmed this. Will work on a fix ASAP.

**Comment by bigtimebuddy** [comment]
Thanks @RFitz and @dan335, got in a fix for that. 

@dan335 could you just double-check this build fixes your issue:
https://pixijs.download/fix-ticker/pixi.js

**Comment by dan335** [comment]
Bad news, not fixed.

````

pixi.js:26622 Uncaught TypeError: this.fn is not a function
    at TickerListener.emit (pixi.js:26622)
    at Ticker.update (pixi.js:26460)
    at Ticker._tick (pixi.js:26196)
emit @ pixi.js:26622
update @ pixi.js:26460
Ticker._tick @ pixi.js:26196
````

````
TickerListener.prototype.emit = function emit(deltaTime) {
    if (this.context) {
      this.fn.call(this.context, deltaTime);
    } else {
      this.fn(deltaTime);
    }
````

**Comment by bigtimebuddy** [comment]
@dan335 bummer. Can you please give me some sample code or create a fiddle? There might be a use-case in your code that I'm not anticipating. Would like to get this patched ASAP. Please let me know.
