### ISSUE TITLE
Browserify bundling fails when using pixi from node_modules

### ISSUE THREAD

**Issue by Zenext** [pixijs/pixi.js#3213]
Hi guys,

So I am facing annoying problem after upgrading to v4.1.0. If I require pixi from node_modules and not use binaries directly it ruins my browserify bundle throwing 

`>> Error: Cannot find module 'babelify' from 'C:\Users\Artjom\test\node_modules\pixi.js'`

Happens because my browserify task sees 'browserify' property in pixis package.json and tries to do the transform, but babelify and its presets are included as dev dependencies only. And I am not using ES6 on my side.

Also, `"main": "./bin/pixi.min.js",` shouldn't it be pointing to entry point? Like is used to be before in v3
`"main": "./src/index.js",`?

Just want some clarification on this one :)

**Comment by jonaswalekvist** [comment]
Hello, this is a problem for me too and is still there in v4.1.1. Manually editing the package.json in the manner @Zenext describe (moving babel to dependencies and changing "main") solves the problem, though it's not a very nice solution for lots of reasons. Can you please fix this to your next release?

And btw thanks for a awesome project. My professional life would be way less enjoyable without Pixi.

**Comment by englercj** [comment]
Some context behind why `main` points to the built file:

https://github.com/pixijs/pixi.js/pull/2981
https://github.com/pixijs/pixi.js/pull/3239

I think the solution here is to add a `browser` field so that browserify uses the source and everything else uses the built file. If you add `"browser": "./src/index.js"` does that fix your issue?

**Comment by jonaswalekvist** [comment]
Yes that seams to work. Though babelify and it's preset is needed. Is there a problem with adding them as a dependency instead of dev-dependency?

**Comment by staff0rd** [comment]
This looks to be fixed via #3289, can anyone confirm?

**Comment by bigtimebuddy** [comment]
This has been fixed in 4.2.2.
